export default {
  id: 'nextjs',
  name: 'Next.js (Turbo)',
  image: 'node:20-alpine',
  language: 'typescript',

  entrypoint: ['sh'],
  cmd: ['-c', 'tail -f /dev/null'],

  port: 3000,

  setupScript: `
set -e

PORT=3000
HOST=0.0.0.0

echo "🚀 Setting up Next.js (Turbo mode)..."

# Create app manually for reliability
if [ ! -f package.json ]; then
  echo "📦 Scaffolding Next.js app..."
  
  # 1. package.json
  cat > package.json << 'JSON'
{
  "name": "next-app",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "14.1.0",
    "react": "^18",
    "react-dom": "^18"
  },
  "devDependencies": {
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "typescript": "^5",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.3.0"
  }
}
JSON

  # 2. tsconfig.json
  cat > tsconfig.json << 'JSON'
{
  "compilerOptions": {
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
JSON

  # 3. Create app structure
  mkdir -p app
  
  cat > app/layout.tsx << 'TSX'
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next.js App",
  description: "Generated by Web IDE",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
TSX

  cat > app/page.tsx << 'TSX'
export default function Home() {
  return (
    <main style={{ padding: '2rem', fontFamily: 'system-ui' }}>
      <h1>Welcome to Next.js!</h1>
      <p>Start editing to see some magic happen.</p>
    </main>
  );
}
TSX

  cat > app/globals.css << 'CSS'
@tailwind base;
@tailwind components;
@tailwind utilities;
CSS

  # 4. Tailwind config
  cat > tailwind.config.ts << 'TS'
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
};
export default config;
TS

  cat > postcss.config.js << 'JS'
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
};
JS

else
  echo "✅ package.json exists, skipping scaffold"
fi

# Install deps once
if [ ! -f node_modules/.bin/next ]; then
  echo "📥 Installing dependencies..."
  npm install
  # Ensure permissions
  chmod -R 777 node_modules/.bin || true
fi

# Update scripts (Turbo enabled)
# Scripts are standard

# Env vars for Docker / Web IDE file watching
cat > .env.local << 'EOF'
CHOKIDAR_USEPOLLING=true
WATCHPACK_POLLING=true
EOF

# Minimal Next config (Turbo-compatible) with Polling
cat > next.config.js << 'EOF'
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  webpack: (config) => {
    config.watchOptions = {
      poll: 1000,
      aggregateTimeout: 300,
    }
    return config
  },
}

module.exports = nextConfig
EOF

cat > start.sh << 'EOF'
#!/bin/sh
# Kill process on port 3000 if it exists (fixes EADDRINUSE on refresh)
pid=$(netstat -nlp | grep :3000 | awk '{print $7}' | awk -F'/' '{print $1}')
if [ -n "$pid" ]; then
  kill -9 $pid || true
fi

echo "🚀 Starting Next.js..."
exec npm run dev -- -H 0.0.0.0 -p 3000
EOF
chmod +x start.sh

echo "✅ Turbo setup complete. Running on port 3000"
  `.trim(),

  startCommand: './start.sh',
};
